//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizzeria
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zamówienia
    {
        public int id_zamów { get; set; }
        public int id_kontakt { get; set; }
        public string Adres { get; set; }
        public string Telefon { get; set; }
    
        public virtual Kontakty Kontakty { get; set; }
    }
}
